title: Nominal 2/3 degree global configuration for CESM/MOM6
author: The Ocean Model Working Group
logo: ncar_logo.png
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/NCAR/tx2_3  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_edit_page_button : true
  use_issues_button    : true
  home_page_in_navbar  : false
